BBreaker: brick.o input.o events.o raster.o model.o render.o balBit.o font.o psg.o music.o effects.o splash.o setScrn.o vector.o vbl_isr.o
	cc68x -g brick.o input.o events.o raster.o model.o balBit.o render.o font.o  psg.o music.o effects.o splash.o setScrn.o vector.o vbl_isr.o -o BBreaker

splash.o: splash.c splash.h 
	cc68x -g -c splash.c
    
psg.o: psg.c psg.h 
	cc68x -g -c psg.c
    
music.o: music.c music.h
	cc68x -g -c music.c

effects.o: effects.c effects.h
	cc68x -g -c effects.c    

brick.o: brick.c brick.h
	cc68x -g -c brick.c

input.o: input.c input.h
	cc68x -g -c input.c
	
events.o: events.c events.h
	cc68x -g -c events.c
	
raster.o: raster.c raster.h
	cc68x -g -c raster.c

render.o: render.c render.h
	cc68x -g -c render.c    
	
model.o: model.c model.h
	cc68x -g -c model.c
	
balBit.o: balBit.c balBit.h
	cc68x -g -c balBit.c
	
font.o: font.c font.h
	cc68x -g -c font.c

vector.o: vector.c vector.h
	cc68x -g -c vector.c
	
setScrn.o: setScrn.s
	gen -D -L2 setScrn.s

vbl_isr.o: vbl_isr.s
	gen -D -L2 vbl_isr.s
