tst_psg: tst_psg.o psg.o music.o effects.o 
	cc68x -g tst_psg.o psg.o music.o effects.o -o tst_psg

tst_psg.o: tst_psg.c psg.h music.h effects.h 
	cc68x -g -c tst_psg.c

psg.o: psg.c psg.h 
	cc68x -g -c psg.c
	
music.o: music.c music.h
	cc68x -g -c music.c

effects.o: effects.c effects.h
	cc68x -g -c effects.c    

	
	
	
