tst_mdl: tst_mdl.o events.o raster.o model.o 
	cc68x -g tst_mdl.o events.o raster.o model.o  -o tst_mdl

tst_mdl.o: tst_mdl.c events.h model.h raster.h 
	cc68x -g -c tst_mdl.c

events.o: events.c events.h model.h
	cc68x -g -c events.c
	
raster.o: raster.c raster.h
	cc68x -g -c raster.c
    
model.o: model.c model.h
	cc68x -g -c model.c
